### ISSUE TITLE
Feature Request & Question

### ISSUE THREAD

**Issue by Rabbit0w0** [Suwings/MCSManager-UI#1]
### Question

不进行再分发是否需要提供完整源代码

### Feature Request

会不会支持多语言

**Comment by Suwings** [comment]
根据开源协议，对代码修改后应该也要提供源代码，但是着点在国内我并不奢求，内部使用的话无需过多关注。但必须提供版权声明，次协议主要针对的是使用此面包魔改后声称是自己开发并进行售卖的对象。

这个版本主要面向中国市场，不会提供多语言。

**Comment by Rabbit0w0** [comment]
By the way 是否会添加更完善的api接口

**Comment by Suwings** [comment]
> By the way 是否会添加更完善的api接口

当然。 这一次采用的是http的接口方式，不是8.0版本的websocket方式。

基本上Web程序就已经自带API接口了，只需在使用时时候验证一次身份就可以了。

**Comment by Rabbit0w0** [comment]
是否会放出完整的api文档

**Comment by Suwings** [comment]
当然会，不过也得等API稳定了之后才会开始写API文档。
