### ISSUE TITLE
更加响应的UI

### ISSUE THREAD

**Issue by AlexanderMC8533** [Suwings/MCSManager-UI#2]
在8的时候，UI界面比较生硬，希望9能灵活一点

**Comment by Suwings** [comment]
UI 界面设计不妥之处能否具体说明，否则仅凭生硬两字无法很好的优化改进。

**Comment by AlexanderMC8533** [comment]
手机端侧边栏入场是直接跳出来，然后进控制台容易卡一下





------------------ 原始邮件 ------------------
发件人: Suwings ***@***.***&gt;
发送时间: 2021年8月7日 09:28
收件人: Suwings/MCSManager-UI ***@***.***&gt;
抄送: AlexanderMC8533 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Suwings/MCSManager-UI] 更加响应的UI (#2)





 
UI 界面设计不妥之处能否具体说明，否则仅凭生硬两字无法很好的优化改进。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
